
# .gitlab-ci.yml

stages:
  - health-check

check-auth-service:
  stage: health-check
  tags:
    - deepak-runner-root
  script:
    - curl -f http://auth-service:5001/health

check-order-service:
  stage: health-check
  tags: 
    - deepak-runner-root
  script:
    - curl -f http://order-service:5002/health

check-recommendation-service:
  stage: health-check
  tags: 
    - deepak-runner-root
  script:
    - curl -f http://recommendation-service:5003/health
